<a href="https://colab.research.google.com/github/jamshid719/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [6]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [10, 20, 30, 40, 50, 60, 70]
}

df = pd.DataFrame(mydataset) # datani table kurinishda qb beradi
print(df)

      cars  counts
0      BMW      10
1    Volvo      20
2     Ford      30
3    Tesla      40
4  Ferrari      50
5     Ford      60
6      BMW      70

In [15]:
df.head()  # default 5 rows //df.head(2) => bowidan 2 ta // df.head(0) - faqat key nomini olib beradi // df.head(-1) => oxiridan 1tasini qoldirib qolgan hammasini olib beradi.

      cars  counts
0      BMW      10
1    Volvo      20
2     Ford      30
3    Tesla      40
4  Ferrari      50

In [16]:
df.tail()  # default 5 rows. //df.tail(2) => ohiridan 2 ta // df.tail(0) - faqat key nomini olib beradi // df.tail(-1) => boshidan 1tasini qoldirib qolgan hammasini olib beradi.

      cars  counts
2     Ford      30
3    Tesla      40
4  Ferrari      50
5     Ford      60
6      BMW      70

In [18]:
df.shape # bu property shape ni ob beradi. yani 7ta qator, 2ta ustun

(7, 2)

In [19]:
df.columns # columnslarni ob beradi va type ni ham

Index(['cars', 'counts'], dtype='object')

In [21]:
df.dtypes # columnlarni typeni olib beradi

cars      object
counts     int64
dtype: object

In [23]:
df.describe() # statistik summary beradi(default holatda faqat number column un)

          counts
count   7.000000
mean   40.000000
std    21.602469
min    10.000000
25%    25.000000
50%    40.000000
75%    55.000000
max    70.000000

In [24]:
df.describe(include='all') # statistik summary beradi(text column un ham)

       cars     counts
count     7   7.000000
unique    5        NaN
top     BMW        NaN
freq      2        NaN
mean    NaN  40.000000
std     NaN  21.602469
min     NaN  10.000000
25%     NaN  25.000000
50%     NaN  40.000000
75%     NaN  55.000000
max     NaN  70.000000

In [27]:
df.iloc[1:4] #bu 1-rowda gi malumotlarni chiqarib beradi, //df.iloc[2] 2-indexdagi malumotni kursatadi
             #//df.iloc[1:4] bu 2dan 4 qatorgacha datalarni kursatadi //df.iloc[2:] bu 3 qatordan hammasini olib beradi

    cars  counts
1  Volvo      20
2   Ford      30
3  Tesla      40

In [34]:
df.loc[2:5, "cars"]  # bunda hamma qatorni va cars column ni malumotlarini olib beradi.
                  # df.loc[2, "cars"] 3-row dagi datani olib keladi
                  # df.loc[2:5, "cars"] 3-row dan 6-rowgacha datani olib keladi

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [35]:
df.head(10)

      cars  counts
0      BMW      10
1    Volvo      20
2     Ford      30
3    Tesla      40
4  Ferrari      50
5     Ford      60
6      BMW      70

In [37]:
#Conditions(conditional operation or filtering)

df[df["counts"] > 30] # df["counts"] uzini qilsak true/false sifatida outputni chiqaradi, agar df urab olsak qiymatlarni uzini chiqaradi(30dan katta bulgan).

      cars  counts
3    Tesla      40
4  Ferrari      50
5     Ford      60
6      BMW      70

In [ ]:
df.mean(numeric_only=True) #qavsga numeric_only=True quyish kk, bulmasa err beradi. (urtacha qiymat)

In [38]:
df.sum() # har bir column ning yigindisini chiqaradi.(df.min(), df.max())

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                280
dtype: object

In [39]:
df.median(numeric_only=True) # numberlarni tartiblab urtadagi qiymatni olib beradi

counts    40.0
dtype: float64

In [40]:
df.count() # datasetdan None, NAN, Null larni chiqarib beradi, bizni datasetda yuq.

cars      7
counts    7
dtype: int64

In [41]:
df.std(numeric_only=True) # standart deviation

counts    21.602469
dtype: float64

In [44]:

data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [46]:
#datalarni cleaning qilish methodi(tekshiriw)

df_missing.isnull().sum() # mavjud bulmagan datalarni xisoblaydi.
                          # df_missing.isnull() bulsa, yuq datalarni true qb, borlarini false qilib chiqaradi

cars      2
counts    2
dtype: int64

In [47]:
df_missing.dropna() # faqat mavjud datalarni olib beradi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [48]:

df_missing.dropna(how="all") # 3 qatorni olib tashlaydi, chunki shu qatorda ham "cars" da ham "count" data yuq

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [50]:
df_missing.dropna(axis=1) # data yuq bulgan columnlarni butunlay uchirib tashlaydi

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [51]:
df_missing.dropna(subset=['counts']) # faqat countsda yuq datalarni olib tashlaydi, "cars" columni tekshirmaydi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0

In [52]:
df_missing.fillna(0) # mavjud bulmagan kataklarga 0 quyib chiqadi.(0 urniga harqanday value quyish mumkin, kop holatlarda "unknown" ham quyib ketadi)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2        0     0.0
3    Tesla     8.0
4  Ferrari     1.0
5        0     9.0
6     Ford     0.0

In [53]:
df_missing.fillna({"cars": "unknown", "counts": 0}) # cars ga "unknown",  "counts"ga 0 quyadi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [57]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head(10)

# df = pd.read_excel("Titanic-Dataset.xlsx")
# df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [58]:
df.to_excel("output.xlsx") # export excel formatda

In [62]:
# Series=> 1D arraylar bn ishlanadi
cars = pd.Series(['BMW', 'Tesla', 'Ferrari'])
print(cars)                                  # lekin Series dan kura dataframe ishlatiladi.

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [64]:
cars_series = data_with_missing["cars"]
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']